import os
import rmsynth
from qiskit.qasm2 import dump

def optimize_with_rmsynth(input_file):
    output_file = input_file.replace(".qasm", "_final.qasm")
    
    if not os.path.exists(input_file):
        print(f"⚠️ File not found: {input_file}")
        return

    print(f"🚀 Optimizing {input_file} via Reed-Muller decoding...")
    try:
        # 1. Load the circuit into rmsynth format
        circuit = rmsynth.Circuit.from_qasm(input_file)
        
        # 2. Extract phase coefficients (Phase Polynomial representation)
        # This is the 'mature' method mentioned in the challenge [cite: 10, 101]
        coeffs = rmsynth.extract_phase_coeffs(circuit)
        
        # 3. Optimize the coefficients using Reed-Muller decoding
        # This targets the T-count metric [cite: 80, 101]
        optimized_coeffs = rmsynth.optimize_coefficients(coeffs)
        
        # 4. Synthesize back to a Clifford+T circuit [cite: 6, 96]
        optimized_circuit = rmsynth.synthesize_from_coeffs(optimized_coeffs)
        
        # 5. Save the final QASM
        optimized_circuit.save_qasm(output_file)
        
        t_before = rmsynth.t_count_of_coeffs(coeffs)
        t_after = rmsynth.t_count_of_coeffs(optimized_coeffs)
        print(f"✨ Created: {output_file} | T-count: {t_before} -> {t_after}")

    except Exception as e:
        print(f"⚠️ Optimization failed for {input_file}: {e}")

# Process the files generated by your test.py
files = [
    "01_controlled_y.qasm", "02_cry_pi_7.qasm", "03_exp_zz.qasm",
    "04_exp_h1.qasm", "05_swap_exact.qasm", "06_ising.qasm",
    "07_state_prep.qasm", "09_qft.qasm", "10_random.qasm", "11_diagonal.qasm"
]

for qfile in files:
    optimize_with_rmsynth(qfile)